<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="do" title="<?php /* @escapeNotVerified */ echo __('Update My Wish List') ?>" class="action update">
        <span><?php /* @escapeNotVerified */ echo __('Update My Wish List') ?></span>
    </button>
<?php endif;?>