<?php 

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<a style="margin-bottom: 25px" type="button" id="wishlist_category_button" href="<?php echo $block->getUrl('demowishlist/index/index'); ?>" title="<?php echo __('Add New Wishlist Category') ?>" class="action tocart primary">
    <span><?php echo __('Add New Wishlist Category') ?></span>
</a>