<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="pc2015-select-menu-search">
    <input class="pc2015-zip-1" type="text" maxlength="7" id="zip" name="zip">
    <!--<input class="pc2015-zip-2" type="text" maxlength="4" id="zip2">-->
    <a href="#" onclick="doSearch();" class="pc2015-search pc2015-designed" id="shop_search_1">Search</a>
</div>
<div class="result-search" id="result">
    
</div>


<script type="text/javascript">
    
    function doSearch() {
        var zip_code = jQuery("#zip").val();
        //data = jQuery(this).serialize();
        jQuery.ajax({
            type: "GET",
            data: { zip: zip_code},
            url:  "postcode/index/search",
            dataType: "json",
            success: function (result) { 
                
                var url = JSON.stringify(result);
                alert(zip_code);
                jQuery('#result').html("<a href=" + url +" target='_blank'>" + result + "</a>");
            },
            error: function (request, status, error) {
                alert(request.responseText);
            }
        });
    }

</script>

