<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<div class="pc2015-select-menu-search">
    <input class="pc2015-zip-1" type="text" maxlength="7" id="zip1">
    <!--<input class="pc2015-zip-2" type="text" maxlength="4" id="zip2">-->
    <a href="#" class="pc2015-search pc2015-designed" id="shop_search_1">Search</a>
</div>