<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
if($block->checkCookie()== false){
?>

<div class="pc2015-select-menu">
    <div class="pc2015-select-menu-search">
        <input class="pc2015-zip-1" type="text" maxlength="3" id="zip1">
        <input class="pc2015-zip-2" type="text" maxlength="4" id="zip2">
        <a href="#" onclick="doSearch();" class="pc2015-search" id="shop_search_1">検索する</a>
        <a href="https://www.post.japanpost.jp/zipcode/index.html" target="_blank" class="pc2015-zip-search">郵便番号検索</a>

        <input type="hidden" id="SearchDeliveryShop_ErrorMessage" value="郵便番号を正しく入力してください。"></input>
    </div>
    <div style="clear: both"></div>
    <div class="pc2015-select-menu-result">
        <ul id="shop_search_result_list_area">
      
        </ul>
        <a class="result-search" id="result" />
    </div>
</div>



<script type="text/javascript">
    
    function doSearch() {
        
        var zip_code = jQuery("#zip1").val() + jQuery("#zip2").val();
        var is_zip_match = true;
        if(zip_code.match(/[^1234567890]/)){
            is_zip_match = false;
        }
        if (!zip_code.match(/^\w{7}$/)) {
            is_zip_match = false;
        }
        if(!is_zip_match){
            alert(jQuery("#SearchDeliveryShop_ErrorMessage").val());
            return false;
        }
        jQuery.ajax({
            type: "GET",
            data: { zip: zip_code},
            url:  "postcode/index/search",
            dataType: "json",
            async: false,
            cache: false,
            success: function (result) { 
                
                //var url = JSON.stringify(result);
                jQuery('.pc2015-select-menu-result').attr("style", "display: block");
                var html ="";
                for (var key in result) {
                    if(key == 0){
                        html += "<li><span><input id='radio[" + key + "]' type='radio' name='shopcategory' value='" + result[key] + "' checked='checked' /></span>" + result[key] +"</li>";
                    }else{
                        html += "<li><span><input id='radio[" + key + "]' type='radio' name='shopcategory' value='" + result[key] + "' /></span>" + result[key] +"</li>";
                    }
                    
                }
                var category = "";
                jQuery('#shop_search_result_list_area').html(html);
                category = jQuery('input:radio:checked').val();
                jQuery('#result').attr("href", category);
                jQuery('#result').html("お店を見る");
                
                var $radios = jQuery('input[name=shopcategory]').change(function () {
                    category = $radios.filter(':checked').val();
                    
                });
                
                jQuery('#result').attr("href", "#");
                jQuery('#result').click(function(){
                    console.log(category);
                    saveCookie(category);
                    window.location.href = category;
                });
                
            },
            error: function (request, status, error) {
                alert(request.responseText);
            }
        });
    }
    
    function saveCookie(category){
        jQuery.ajax({
            type: "GET",
            data: { url: category},
            url:  "postcode/index/savecookie",
            async: false,
            cache: false,
            success: function(result){
                
                    
                console.log(result);
            },
            error: function (request, status, error) {
                alert("Save"+request.responseText);
            }
        });
        
    }
    
    

</script>
<?php 

}else{
?>
<div class="img_default">
    <img src="<?php echo $this->getViewFileUrl('Store_PostCode::images/13344.jpg'); ?>" />
</div>
<?php
}